### ISSUE TITLE
Does not build in sbcl 2.0.9 - :initform/:type conflict

### ISSUE THREAD

**Issue by quicklisp** [j3pic/cl-async-await#2]
https://github.com/j3pic/cl-async-await/blob/1406a59fd4087b9013287be8145be5c5d31a1556/promise.lisp#L18

I get this: `Constant NIL conflicts with its asserted type SB-THREAD:THREAD.`

Log here: http://report.quicklisp.org/2020-09-29/failure-report/cl-async-await.html#cl-async-await

**Comment by j3pic** [comment]
How about now?

**Comment by quicklisp** [comment]
Looks good to me, thanks!
